# Site settings
title: CS10 | Spring 2015
email: info@cs10.org
description: > # CS10, The Beauty and Joy of Computing, is an introductory
    computer science class designed for anyone and everyone. The Beauty and
    Joy of Computing is an AP Computer Science Principles class.
keywords: "CS10, UC, Berkeley, CS, computer science, BJC, computing, education, Snap!, CS Principles, AP"
baseurl: "/sp15"
url: "http://cs10.org"

# Build settings
markdown: kramdown


# CSS Style
sass:
    style: :compressed
    sass_dir: assets/_sass

# TODO: TA Collections
# collections:
    # - tas:
        # output: true